### ISSUE TITLE
High CPU load when idle

### ISSUE THREAD

**Issue by Lodger-test** [MusicPlayerDaemon/mpdscribble#61] opened 2024-08-09 11:51 UTC
**Version:** mpdscribble 0.25-2
**Mode:** runs as an enabled mpdscribble.service (/usr/bin/mpdscribble --no-daemon)
**System:** Arch GNU/Linux [x86_64]
**Bundle:** mpd 0.23.15-5 + mpc 0.35-1 + ncmpc 0.49-2 + mpdscribble 0.25-2

**Actual behavior:**

100% load of one CPU core  when mpd playback is paused or stopped.

**How to reproduce:** 

Add some tracks to playlist, play them and pause or stop the playback. In a while you should hear the cooler increasing noise and then you could see a high CPU load (top, htop) by mpdscribble.

**Comment by MaxKellermann** [comment] 2024-08-09 19:02
Probably duplicate of https://github.com/MusicPlayerDaemon/mpdscribble/issues/60 and it's really a CURL bug.

**Closed by MaxKellermann** 2024-08-09 19:02 UTC

**Comment by Lodger-test** [comment] 2024-08-09 19:55
> Probably duplicate of #60 and it's really a CURL bug.

Thanks. Updated curl to 8.9.1-2, hope it will solve the issue.
